### ISSUE TITLE
Program output should be JSON

### ISSUE THREAD

**Issue by brunoais** [w1kl4s/DescriptionGenerator#1]
https://github.com/w1kl4s/DescriptionGenerator/blob/master/src/filewrite.py#L2
See: https://docs.python.org/3/library/json.html#json.dump

**Comment by w1kl4s** [comment]
I don't intend on keeping output like that. Writing to TXT is only a temporary solution that allows for clear line-by-line view of obtained data.

Next versions will probably use one of the templates from the wiki, and write everything to HTML file ready to be offered on tracker.
